# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Movies CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Installing npm
      run: npm install
    
    - name: Runing the unit test
      run: npm run test:unit
    
    - name: Print my username
      env:
        username: "VasStud"
      run: echo "$username"
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy to Production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.SERVICE_ID }}
          
  ui_test:
   runs-on: ubuntu-latest
   needs: [deploy]
   strategy:
      matrix:
        node-version: [14.x]
   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Installing npm
      run: npm install
      
    - name: Install playwright browsers
      run: npx playwright install --with-deps
    
    - name: Runing the ui tests
      run: npm run test:ui
